---
title: "Starwars Flex Dashboard"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
    theme: sandstone
    favicon: favicon.ico
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(reshape2)
library(dplyr)
library(plotly)

pdf(NULL)

starwars.load <- starwars %>%
  mutate(films = as.character(films),
         vehicles = as.character(vehicles),
         starships = as.character(starships),
         name = as.factor(name))

swInput <- reactive({
  
  starwars <- starwars.load %>%
    # Slider Filter
    filter(birth_year >= input$birthSelect[1] & birth_year <= input$birthSelect[2])
  # Homeworld Filter
  if (length(input$worldSelect) > 0 ) {
    starwars <- subset(starwars, homeworld %in% input$worldSelect)
  }
  
  return(starwars)
})
# Reactive melted data
mwInput <- reactive({
  swInput() %>%
    melt(id = "name")
})
```

Sidebar {.sidebar}
=====================================

```{r}
selectInput("worldSelect",
               "Homeworld:",
               choices = sort(unique(starwars.load$homeworld)),
               multiple = TRUE,
               selectize = TRUE,
               selected = c("Naboo", "Tatooine"))
   # Birth Selection
   sliderInput("birthSelect",
               "Birth Year:",
               min = min(starwars.load$birth_year, na.rm = T),
               max = max(starwars.load$birth_year, na.rm = T),
               value = c(min(starwars.load$birth_year, na.rm = T), max(starwars.load$birth_year, na.rm = T)),
               step = 1)
```

Plots
=====================================

Row 
-------------------------------------

###

```{r}
renderValueBox({
  
})
```

###

```{r}

```

### Worlds Selected

```{r}

```

Row {.tabset .tabset-fade}
-------------------------------------

### Mass

```{r}

```

### Height

```{r}

```

Table
=====================================

Row 
-------------------------------------

### Table 

```{r}

```